name: .NET VSTest Example

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Show workspace structure
        run: |
          pwd
          ls -R
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore SampleAppSolution/SampleApp/SampleApp.csproj

      - name: Build project
        run: dotnet build SampleAppSolution/SampleApp/SampleApp.csproj --configuration Release

      - name: Build test project
        run: dotnet build SampleAppSolution/SampleApp.Tests/SampleApp.Tests.csproj --configuration Release

      - name: List test DLLs
        run: Get-ChildItem -Path . -Recurse -Filter *.dll
        shell: pwsh

      - uses: microsoft/vstest-action@v1.0.0
        with:
          testAssembly: 'SampleAppSolution/SampleApp.Tests/bin/Release/net8.0/SampleApp.Tests.dll'
      # or wherever your build output actually places the file
          searchFolder: '.'
          resultLogsArtifactName: vs-test-result-logs
          ifNoFilesFound: warn