name: build reusable workflow file
on:
  workflow_call:
    inputs:
      envi:
        required: true
        type: string
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: print env
        run: echo "building ${{ inputs.env}}"