name: Main Workflow

on:
  push:

jobs:
  call-reusable-a:
    uses: ./.github/workflows/reusable-a.yml
    with:
      demo: firstcalling
  call-reusable-b:
    uses: ./.github/workflows/reusable-b.yml
    with:
      demo: secondcalling
  call-reusable-c:
    uses: ./.github/workflows/reusable-c.yml
    with:
      demo: thirdcalling
  call-reusable-d:
    uses: ./.github/workflows/reusable-d.yml
    with:
      demo: fourthcalling