name: Conditional Reusable Workflow Caller

on:
  workflow_dispatch:
    inputs:
      run_a:
        description: "Run workflow A?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  decide:
    runs-on: ubuntu-latest
    outputs:
      run_a: ${{ github.event.inputs.run_a }}
    steps:
      - run: echo "Decision made!"

  call-a:
    needs: decide
    if: needs.decide.outputs.run_a == 'true'
    uses: ./.github/workflows/reusable-a.yml
    with:
      envi: test

  call-b:
    needs: decide
    if: needs.decide.outputs.run_a != 'true'
    uses: ./.github/workflows/reusable-b.yml
    with:
      demo: thistest