name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      TestLevel:
        description: "Test Level"
        required: true
        type: choice
        default: Fortified
        options:
          - Fortified
          - Deferred
          - Deficient    

jobs:
  call-reusable-a:
    uses: ./.github/workflows/reusable-a.yml
    with:
      demo: firstcalling

  call-reusable-b:
    uses: ./.github/workflows/reusable-b.yml
    with:
      demo: secondcalling

  call-reusable-c:
    uses: ./.github/workflows/reusable-c.yml
    with:
      demo: thirdcalling

  call-reusable-d:
    needs: [call-reusable-a, call-reusable-b]
    
    if: ${{ needs.call-reusable-a.result == 'success' || needs.call-reusable-b.result == 'success' }}
    uses: ./.github/workflows/reusable-d.yml
    with:
      demo: thiisfourthcalling
    