name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      TestLevel:
        description: "Test Level"
        required: true
        type: choice
        default: Fortified
        options:
          - Fortified
          - Deferred
          - Deficient    
  schedule:
    - cron: '*/15 * * * *'   # Every 5 minutes
  env:
    TEST_LEVEL: ${{ github.event.inputs.TestLevel || 'Fortified' }}

jobs:
  call-reusable-a:
    uses: ./.github/workflows/reusable-a.yml
    with:
      demo: firstcallinggggggg

  call-reusable-b:
    uses: ./.github/workflows/reusable-b.yml
    with:
      demo: secondcalling11111111

  call-reusable-c:
    uses: ./.github/workflows/reusable-c.yml
    with:
      demo: thirdcalling

  call-reusable-d:
    needs: [call-reusable-a, call-reusable-b]
    if: |
      github.event_name == 'schedule' ||
      (
        github.event.inputs.TestLevel != 'Deficient' &&
        (
          (github.event.inputs.TestLevel == 'Fortified' && needs.call-reusable-a.result == 'success') ||
          (github.event.inputs.TestLevel == 'Deferred' && needs.call-reusable-b.result == 'success')
        )
      )
    uses: ./.github/workflows/reusable-d.yml
    with:
      demo: thiisfourthcalling