# name: Main Workflow

# on:
#   push:

env:
  MY_ENV_VAR: "hello-from-global-env"   # <-- defined at workflow level

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-a.yml
    with:
      MY_ENV_VAR: ${{ env.MY_ENV_VAR }} # <-- this works!