on:
  workflow_call:
    inputs:
      MY_ENV_VAR:
        required: true
        type: string

jobs:
  print-env:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: ${{ inputs.MY_ENV_VAR }}
    steps:
      - run: echo "MY_ENV_VAR is $MY_ENV_VAR"