# .github/workflows/reusable-a.yml
on:
  workflow_call:
    inputs:
      MY_ENV_VAR:
        required: true
        type: string

jobs:
  show-input:
    runs-on: ubuntu-latest
    steps:
      - run: echo "MY_ENV_VAR is ${{ inputs.MY_ENV_VAR }}"