name: reusable build
on:
  workflow_call:
    inputs:
      demo:
        required: true
        type: string
      buildnumber:
        required: true
        type: string
env:
  buildnumber: ${{ inputs.buildnumber }}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: print env
        run: |
          echo "building ${{ inputs.demo}}"
          echo "buildnumber is $env:buildnumber"
          
