name: VSTest with Build Tools

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Install Visual Studio Build Tools
      run: |
        # Download and install Build Tools
        Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "vs_buildtools.exe"
        Start-Process -FilePath "vs_buildtools.exe" -ArgumentList "--quiet", "--wait", "--add", "Microsoft.VisualStudio.Workload.MSBuildTools", "--add", "Microsoft.VisualStudio.Workload.VCTools" -NoNewWindow -Wait
        
    - name: Add VSTest to PATH
      run: |
        $vstestPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow"
        echo $vstestPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "this vssbuild: $vstestPath"
    - name: Print MSBuild Path using where
      run: |
        where msbuild
      shell: cmd
        
    # - name: Build and run tests
    #   run: |

    #     # #msbuild YourSolution.sln /p:Configuration=Release
    #     # vstest.console.exe YourTestProject\bin\Release\YourTestProject.dll